apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: sample
  name: sample-clusterrole
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
