apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-clusterrolebinding
  namespace: sample
subjects:
  - kind: ServiceAccount
    name: sample-svc
    namespace: sample
roleRef:
  kind: ClusterRole
  name: sample-clusterrole
  apiGroup: rbac.authorization.k8s.io
